version: "3.8"
services:
    web:
        build: .
        ports:
            - 8080:8080
        environment:
            - DEBUG
            - SECRET_KEY
            - ALLOWED_HOSTS
            - DATABASE_URL=psql://postgres:test_password@db:5432/cinema_social_media
            - TMDB_API_KEY
        command: >
            sh -c "cd app
            && python manage.py migrate
            && gunicorn -b 0.0.0.0:8080 cinema_social_media.wsgi"
        depends_on:
        - db
    db:
        image: postgres:12-alpine
        environment:
        - POSTGRES_DB=cinema_social_media
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=test_password
