# Generated by Django 4.0.6 on 2022-07-17 23:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador interno do gênero', primary_key=True, serialize=False)),
                ('tmdb_id', models.BigIntegerField(db_index=True, help_text='Identificador do gênero no TMBD', unique=True, verbose_name='TMDB ID')),
                ('tv', models.BooleanField(default=False, help_text='Identifica se é um gênero de filme ou de série')),
            ],
        ),
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador interno do filme', primary_key=True, serialize=False)),
                ('tmdb_id', models.BigIntegerField(db_index=True, help_text='Identificador do filme no TMBD', unique=True, verbose_name='TMDB ID')),
                ('backdrop_url', models.URLField(verbose_name='URL do Banner')),
                ('poster_url', models.URLField(verbose_name='URL do Poster')),
                ('name', models.CharField(help_text='Nome do filme/série', max_length=255, verbose_name='nome')),
                ('overview', models.TextField()),
                ('vote_average', models.FloatField(verbose_name='média dos votos')),
                ('creation_date', models.DateTimeField(auto_now_add=True, help_text='data de criação interna', verbose_name='data de criação')),
                ('last_update', models.DateTimeField(auto_now=True, help_text='data da última atualização', verbose_name='data de atualização')),
            ],
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
