# Generated by Django 4.0.6 on 2022-07-20 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_genre_title_alter_user_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='external_url',
            field=models.URLField(null=True, verbose_name='URL externa'),
        ),
        migrations.AlterField(
            model_name='title',
            name='backdrop_url',
            field=models.URLField(null=True, verbose_name='URL do Banner'),
        ),
        migrations.AlterField(
            model_name='title',
            name='poster_url',
            field=models.URLField(null=True, verbose_name='URL do Poster'),
        ),
    ]
