# Generated by Django 4.0.6 on 2022-07-20 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_title_external_url_alter_title_backdrop_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='popularity',
            field=models.FloatField(default=0.0, verbose_name='popularidade do título'),
            preserve_default=False,
        ),
    ]
